config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "account#index"

    put "/manager/reports", to: "manager/reports#update"

    devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }, skip: :omniauth_callbacks

    namespace :manager do
      get "/users/search", to: "users#search"
      resources :reports, only: %i(index show update)
      resources :users, only: %i(index show update)
    end

    resources :reports
    resources :account, only: %i(index edit update)
    resources :comments, only: :create
  end
end

app/views/shared/_account_edit.html.erb
<%= form_tag account_path(current_user), method: :put, multipart: true do %>
  <div class="col-md-4">
    <div id="box-avatar-edit">
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar, class: "img-thumbnail", id: "avatar-img" %>
      <% else %>
        <%= image_tag Settings.image.default_avatar, class: "img-thumbnail", id: "avatar-img" %>
      <% end %>
    </div>
    <%= file_field_tag :avatar, accept: Settings.validates.user.avatar_type, id: "input-avatar" %>
  </div>
  <div class="col-md-8">
      <div class="form-group">
        <%= label_tag :name %>
        <%= text_field_tag :name, user.name, class: "form-control", id: "edit-name-account" %>
      </div>
      <div class="form-group">
        <%= label_tag :email %>
        <%= email_field_tag :email, user.email, class: "form-control", id: "edit-email-account" %>
      </div>
      <div class="form-group">
        <%= label_tag :division %>
        <%= text_field_tag :division, user.role, class: "form-control", disabled: true %>
      </div>
      <div class="form-group">
        <%= label_tag :role %>
        <%= text_field_tag :role, division.division_name, class: "form-control", disabled: true %>
      </div>
      <div class="form-group">
        <%= submit_tag t(".save"), class: "btn btn-info", id: "btn-submit-edit-account", disabled: true %>
      </div>
  </div>
<% end %>

app/views/shared/_account_info.html.erb
<div class="col-md-4">
  <% if user.avatar.attached? %>
    <%= image_tag user.avatar, class: "img-thumbnail" %>
  <% else %>
    <%= image_tag Settings.image.default_avatar, class: "img-thumbnail" %>
  <% end %>
</div>
<div class="col-md-8 ">
  <div class="col-md-12 box-info">
    <p><%= t ".name" %></p>
    <%= user.name %>
  </div>
  <div class="col-md-12 box-info">
    <p><%= t ".email" %></p>
    <%= user.email %>
  </div>
  <div class="col-md-12 box-info">
    <p><%= t ".division" %></p>
    <%= division.division_name %>
  </div>
  <div class="col-md-12 box-info">
    <p><%= t ".role" %></p>
    <%= user.role %>
  </div>
</div>

app/views/shared/_comment_form.html.erb
<%= form_tag comments_path, remote: true do %>
  <div class="col-xs-12 form-group">
    <%= text_area_tag :content, "", class: "input-field-comment form-control", id: "input-comment", placeholder: t(".placeholder_input_comment") %>
  </div>
  <%= hidden_field_tag :report_id, params[:id] %>
  <div class="col-xs-12">
    <%= submit_tag t(".comment"), class: "btn btn-primary btn-submit-comment pull-right", id: "btn-submit-comment", disabled: true %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".message_error" %>
      <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_report_comment.html.erb
<div class="card-body">
  <div class="row">
    <div class="col-md-1 padding-0">
      <% if comment.user_avatar.attached? %>
        <%= image_tag comment.user_avatar, class: "img img-circle img-fluid circle-avatar-small" %>
      <% else %>
        <%= image_tag Settings.image.default_avatar, class: "img img-circle img-fluid circle-avatar-small" %>
      <% end %>
    </div>
    <div class="col-md-11 padding-0">
      <div class="col-md-12">
        <p>
          <strong><%= comment.user_name %></strong>
        </p>
      </div>
      <div class="col-md-12">
        <p>
          <%= comment.content %>
        </p>
      </div>
      <div class="col-md-12">
        <p class="text-secondary text-center pull-right">
          <%= time_ago_in_words comment.created_at %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_report_comments.html.erb
<div class="col-xs-12">
  <h3>
    <%= t ".comment" %>
  </h3>
</div>
<div class="col-xs-12">
  <%= render "shared/comment_form", report: report %>
</div>
<div class="col-xs-12 all-comments" id="<%= "all-comments-#{report.id}" %>">
  <%= render partial: "shared/report_comment", collection: comments, as: :comment %>
</div>

app/views/shared/_report_detail.html.erb
<div class="user-info report-detail col-md-12">
  <% if user.avatar.attached? %>
    <%= image_tag user.avatar, class: "img-circle col-md-2 circle-avatar-bigger" %>
  <% else %>
    <%= image_tag Settings.image.default_avatar, class: "img-circle col-md-2 circle-avatar-bigger" %>
  <% end %>
  <div class="col-md-10">
    <div class="col-md-12 box-info">
      <span><%= t ".name" %></span>
      <%= user.name %>
    </div>
    <div class="col-md-12 box-info">
      <span><%= t ".email" %></span>
      <%= user.email %>
    </div>
  </div>
</div>
<div class="report-detail col-md-12">
  <div class="col-md-12 box-info">
    <p><%= t ".today_plan" %></p>
    <%= report.today_plan %>
  </div>
  <div class="col-md-12 box-info">
    <p><%= t ".actual" %></p>
    <%= report.actual %>
  </div><div class="col-md-12 box-info">
    <p><%= t ".reason_not_complete" %></p>
    <%= report.reason_not_complete %>
  </div><div class="col-md-12 box-info">
    <p><%= t ".tomorrow_plan" %></p>
    <%= report.tomorrow_plan %>
  </div>
  <div class="col-md-12 box-info">
    <p><%= t ".free_comment" %></p>
    <%= report.free_comment %>
  </div>
  <div class="col-md-12 box-info">
    <p><%= t ".date_created" %></p>
    <%= report.created_at.strftime Settings.date.validate %>
  </div>
  <div class="col-md-12 box-info">
    <p><%= t ".status" %></p>
    <%= report.status %>
  </div>
</div>

app/views/shared/_search_user.html.erb
<div class="col-md-12">
  <h4><%= t ".user_searching" %></h4>
</div>
<div class="col-md-12">
  <%= text_field_tag :email, "", class: "form-control", id: "input-email-searching", placeholder: t(".type_email"), autocomplete: "off" %>
  <div class="col-md-12 user-searching-result box-show" id="user-searching-result"></div>
</div>