config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "account#index"

    put "/manager/reports", to: "manager/reports#update"

    devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }, skip: :omniauth_callbacks

    namespace :manager do
      get "/users/search", to: "users#search"
      resources :reports, only: %i(index show update)
      resources :users, only: %i(index show update)
    end

    resources :reports
    resources :account, only: %i(index edit update)
    resources :comments, only: :create
  end
end

app/models/report.rb
class Report < ApplicationRecord
  REPORTS_PARAMS = %i(today_plan actual reason_not_complete
    tomorrow_plan free_comment).freeze

  enum status: {waiting: 0, checked: 1, rejected: 2}

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :new_comments, dependent: :destroy

  validates :today_plan, presence: true,
    length: {maximum: Settings.validates.report.max_length}
  validates :actual, presence: true,
    length: {maximum: Settings.validates.report.max_length}
  validates :tomorrow_plan, presence: true,
    length: {maximum: Settings.validates.report.max_length}
  validates :reason_not_complete,
            length: {maximum: Settings.validates.report.max_length}
  validates :free_comment,
            length: {maximum: Settings.validates.report.max_length}

  delegate :name, :email, to: :user, prefix: true

  ransacker :created_at, type: :date do
    Arel.sql("date(reports.created_at)")
  end

  scope :includes_user, ->{includes :user}
  scope :recent_reports, ->{order created_at: :desc}
  scope :active_reports, ->{where deleted: false}
  scope :by_ids, ->(report_ids){where id: report_ids}
  scope :by_users, ->(user_ids){where user_id: user_ids}
  scope :by_date_created, (lambda do |date|
    where("date(created_at) = :date", date: date) if date.present?
  end)
  scope :order_by_created, (lambda do |type_order|
    type_order = type_order.presence || :desc
    order created_at: type_order
  end)
  scope :order_by_status, (lambda do |type_order|
    type_order = type_order.presence || :asc
    order status: type_order
  end)
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :async,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  USERS_PARAMS = %i(name email password password_confirmation avatar).freeze
  PASSWORD_REGEX = Settings.validates.password.regex

  enum role: {member: 0, manager: 1, admin: 2}

  belongs_to :division, optional: true
  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :new_comments, dependent: :destroy
  has_one_attached :avatar

  validates :name, presence: true,
    length: {maximum: Settings.validates.user.max_length_name}
  validates :email, presence: true,
    length: {maximum: Settings.validates.user.max_length_email},
    format: {with: Settings.validates.user.validate_email_regex},
    uniqueness: {case_sensitive: true}
  validates :password, presence: true,
    length: {minimum: Settings.validates.user.min_length_password},
    allow_nil: true
  validates :avatar,
            content_type: {in: Settings.validates.user.avatar_type.split,
                           message: I18n.t("users.avatar_type_validate")}
  validate :password_complexity

  delegate :division_name, to: :division

  before_save :downcase_email

  scope :includes_division, ->{includes :division}
  scope :by_division_id, (lambda do |division_id|
    where(division_id: division_id)
  end)
  scope :like_email, (lambda do |email|
    where("email like :email", email: "%#{email}%") if email.present?
  end)

  class << self
    def from_omniauth auth
      user = User.find_by email: auth.info.email
      return user if user

      omniauth_user auth
    end

    def omniauth_user auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.name = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider
        user.skip_confirmation!
      end
    end
  end

  private

  def downcase_email
    email.downcase!
  end

  def password_complexity
    return unless password.present? && !password.match(PASSWORD_REGEX)

    errors.add :password, I18n.t("validates.password.error_regex")
  end
end

app/controllers/manager/reports_controller.rb
class Manager::ReportsController < ApplicationController
  before_action ->{check_role? :manager}
  before_action :paginate_reports, only: %i(index update)
  before_action :find_report, only: :show

  load_and_authorize_resource

  def index; end

  # rubocop:disable Rails/SkipsModelValidations
  def update
    Report.by_ids(params[:report_ids])
          .update_all status: params[:update_status]
    respond_to do |format|
      format.html{redirect_to manager_reports_path}
      format.js
    end
  end
  # rubocop:enable Rails/SkipsModelValidations

  def show
    checked_new_comment params[:id]
    @user = @report.user
    @comments = Comment.includes_user
                       .by_report_id(params[:id])
                       .order_by_created_at
  end

  private

  def paginate_reports
    select_reports
    per_page = params[:per_page].presence || Settings.paginate.per_page_default
    @reports = @reports.page(params[:page])
                       .per per_page
    return unless params[:show_all]

    @reports = @reports.except :limit, :offset
  end

  def user_in_division
    User.by_division_id(current_user.division_id)
  end

  def find_report
    @report = Report.find_by id: params[:id]
    return if @report

    flash[:danger] = t ".find_report_error"
    redirect_to reports_path
  end

  def select_reports
    users = user_in_division
    @report = Report.ransack params[:q]
    @reports = @report.result
                      .includes(:user)
                      .by_users(users)
                      .active_reports
    return if @report.sorts.present?

    @reports = @reports.order_by_status(:asc)
                       .order_by_created :desc
  end
end

app/controllers/manager/users_controller.rb
class Manager::UsersController < ApplicationController
  before_action ->{check_role? :manager}
  before_action :find_user, only: %i(show update)
  before_action :paginate_members, only: %i(index update)

  load_and_authorize_resource

  def index; end

  def show
    @division = Division.find_by id: @user.division_id
    return if @division

    flash[:danger] = t ".error_division"
    redirect_to manager_users_path
  end

  def update
    if params[:nonremote]
      update_user_nonremote
      redirect_to manager_user_path params[:id]
    else
      @user.update division_id: Settings.division.default
      respond_to do |format|
        format.html{redirect_to manager_users_path}
        format.js
      end
    end
  end

  def search
    @users = User.like_email(params[:key])
                 .member
                 .limit Settings.limit.user_searching
    respond_to do |format|
      format.json{render json: @users}
    end
  end

  private

  def find_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = t ".find_user_error"
    redirect_to manager_users_path
  end

  def paginate_members
    per_page = params[:per_page].presence || Settings.paginate.per_page_default
    @members = User.includes_division
                   .by_division_id(current_user.division_id)
                   .member
                   .page(params[:page])
                   .per per_page
    @managers = User.by_division_id(current_user.division_id)
                    .manager
  end

  def update_user_nonremote
    division_id = if @user.division_id.eql? Settings.division.default
                    current_user.division_id
                  else
                    Settings.division.default
                  end
    @user.update division_id: division_id
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action ->{check_role? :member}
  before_action :paginate_reports, only: %i(index destroy)
  before_action :find_report, except: %i(new create index)
  before_action :belong_to_division?, only: %i(new create)
  before_action :today_reports, only: :new

  load_and_authorize_resource

  def index; end

  def new
    return @report = current_user.reports.build if @today_reports.blank?

    flash[:danger] = t ".error_create_path"
    redirect_to reports_path
  end

  def create
    @report = current_user.reports.build report_params

    if @report.save
      flash[:info] = t ".create_success_notify"
      redirect_to reports_path
    else
      flash.now[:danger] = t ".create_failed_notify"
      render :new
    end
  end

  def show
    checked_new_comment params[:id]
    @user = @report.user
    @comments = Comment.includes_user
                       .by_report_id(params[:id])
                       .order_by_created_at
  end

  def update
    if @report.update report_params
      flash[:success] = t ".edit_report_success"
      redirect_to reports_path
    else
      flash[:danger] = t ".edit_report_faild"
      redirect_to edit_report_path params[:id]
    end
  end

  def edit; end

  def destroy
    @report.update deleted: true
    respond_to do |format|
      format.html{redirect_to reports_path}
      format.js
    end
  end

  private

  def report_params
    params.require(:report).permit Report::REPORTS_PARAMS
  end

  def paginate_reports
    select_reports
    per_page = params[:per_page].presence || Settings.paginate.per_page_default
    @reports = @reports.page(params[:page])
                       .per per_page
  end

  def find_report
    @report = Report.find_by id: params[:id]
    return if @report

    flash[:danger] = t ".find_report_error"
    redirect_to reports_path
  end

  def today_reports
    @today_reports = Report.by_users(current_user.id)
                           .by_date_created(Date.current)
                           .active_reports
  end

  def select_reports
    @report = Report.ransack params[:q]
    @reports = @report.result
                      .by_users(current_user.id)
                      .active_reports
                      .recent_reports
  end
end

app/views/manager/reports/_all_reports.html.erb
<div>
  <h4>
    <%= t ".all_report" %>
    (<span id="num-reports">
      <%= reports.total_count %>
    </span>)
  </h4>
</div>
<%= form_tag manager_reports_path(page: params[:page], date: params[:date], name: params[:name], email: params[:email], status: params[:status], order_status: params[:order_status], order_created: params[:order_created], per_page: params[:per_page], show_all: params[:show_all]), method: :put, remote: true, id: "checkbox-form" do %>
  <button class="btn btn-default report-top-option dropdown-toggle" type="button" data-toggle="dropdown">
    <%= t ".status" %>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= option_update_status_button :checked, Settings.icon.check, t(".checked") %>
    </li>
    <li>
      <%= option_update_status_button :waiting, Settings.icon.spinner, t(".waiting") %>
    </li>
    <li>
      <%= option_update_status_button :rejected, Settings.icon.times, t(".reject") %>
    </li>
  </ul>
  <% if params[:show_all] %>
    <%= link_show_paginate_reports nil, Settings.icon.pager, t(".paginate") %>
  <% else %>
    <%= link_show_paginate_reports true, Settings.icon.list, t(".show_all") %>
  <% end %>
  <%= link_to manager_reports_path(per_page: params[:per_page], show_all: params[:show_all]), class: "report-top-option btn btn-default" do %>
    <i class="fas fa-undo"></i>
    <%= t ".clear" %>
  <% end %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t ".select" %></th>
        <th><%= t ".id" %></th>
        <th><%= t ".name" %></th>
        <th><%= t ".email" %></th>
        <th>
          <%= sort_link report, :created_at, t(".date_created") %>
        </th>
        <th>
          <%= sort_link report, :status, t(".status") %>
        </th>
        <th><%= t ".action" %></th>
      </tr>
    </thead>
    <tbody id="body-report-table">
      <%= render partial: "report_table", collection: reports, as: :report %>
    </tbody>
  </table>
  <% if reports.total_count > Settings.paginate.per_page_default.to_i && params[:show_all].blank? %>
    <div>
      <%= t ".per_page" %>
      <% if params[:per_page].eql? Settings.paginate.per_page_option_1 %>
        <%= link_per_page_manager_reports Settings.paginate.per_page_default %>
        <span><%= Settings.paginate.per_page_option_1 %></span>
      <% else %>
        <span><%= Settings.paginate.per_page_default %></span>
        <%= link_per_page_manager_reports Settings.paginate.per_page_option_1 %>
      <% end %>
    </div>
  <% end %>
<% end %>
<% unless params[:show_all] %>
  <%= paginate reports %>
<% end %>

app/views/manager/reports/_filter_form.html.erb
<div class="input-group" id="form-report-filter">
  <%= search_form_for report, url: manager_reports_path do |f| %>
    <div class="col-xs-4">
      <p>
        <%= t ".date_created" %>
      </p>
      <%= f.date_field :created_at_eq, class: "input-filter-report" %>
    </div>
    <div class="col-xs-4">
      <p>
        <%= t ".status" %>
      </p>
      <%= f.select :status_eq, Settings.select_option.filter_status, {}, { class: "input-filter-report" } %>
    </div>
    <div class="col-xs-4">
      <p>
        <%= t ".email" %>
      </p>
      <%= f.text_field :user_email_cont, class: "input-filter-report" %>
    </div>
    <div class="col-xs-4">
      <p>
        <%= t ".name" %>
      </p>
      <%= f.text_field :user_name_cont, class: "input-filter-report" %>
    </div>
    <%= hidden_field_tag :per_page, params[:per_page] %>
    <div class="col-xs-4 div-submit-filter-report">
      <%= f.submit t(".filter"), class: "btn btn-success" %>
    </div>
  <% end %>
</div></br>

app/views/manager/reports/_report_table.html.erb
<tr id="<%= "report-#{report.id}" %>" class="<%= "report_new_comment" unless report_new_comment(report.id) %>">
  <td>
    <%= check_box_tag "report_ids[]", report.id, false, class: "report-checkbox" %>
  </td>
  <td>
    <%= item_id report_counter, params[:page] %>
  </td>
  <td><%= report.user_name %></td>
  <td><%= report.user_email %></td>
  <td><%= report.created_at.strftime Settings.date.validate %></td>
  <td>
    <%= report.status %>
  </td>
  <td>
    <%= link_to t(".detail"), manager_report_path(report.id) %>
  </td>
</tr>

app/views/manager/reports/index.html.erb
<%= provide :title, t(".title") %>
<div class="div-all-report">
  <h2 class="title-center report-title box-show">
    <%= current_user.division_name %>
  </h2>
  <div class="col-xs-12 box-show">
    <div class="div-report-filter">
      <%= render "filter_form", report: @report %>
    </div>
    <div id="all-report">
      <%= render "all_reports", reports: @reports, report: @report %>
    </div>
  </div>
</div>

app/views/manager/reports/update.js.erb
$("#all-report").html(
  "<%= j render "all_reports", reports: @reports, report: @report %>"
);