config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "account#index"

    put "/manager/reports", to: "manager/reports#update"

    devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }, skip: :omniauth_callbacks

    namespace :manager do
      get "/users/search", to: "users#search"
      resources :reports, only: %i(index show update)
      resources :users, only: %i(index show update)
    end

    resources :reports
    resources :account, only: %i(index edit update)
    resources :comments, only: :create
  end
end

app/models/report.rb
class Report < ApplicationRecord
  REPORTS_PARAMS = %i(today_plan actual reason_not_complete
    tomorrow_plan free_comment).freeze

  enum status: {waiting: 0, checked: 1, rejected: 2}

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :new_comments, dependent: :destroy

  validates :today_plan, presence: true,
    length: {maximum: Settings.validates.report.max_length}
  validates :actual, presence: true,
    length: {maximum: Settings.validates.report.max_length}
  validates :tomorrow_plan, presence: true,
    length: {maximum: Settings.validates.report.max_length}
  validates :reason_not_complete,
            length: {maximum: Settings.validates.report.max_length}
  validates :free_comment,
            length: {maximum: Settings.validates.report.max_length}

  delegate :name, :email, to: :user, prefix: true

  ransacker :created_at, type: :date do
    Arel.sql("date(reports.created_at)")
  end

  scope :includes_user, ->{includes :user}
  scope :recent_reports, ->{order created_at: :desc}
  scope :active_reports, ->{where deleted: false}
  scope :by_ids, ->(report_ids){where id: report_ids}
  scope :by_users, ->(user_ids){where user_id: user_ids}
  scope :by_date_created, (lambda do |date|
    where("date(created_at) = :date", date: date) if date.present?
  end)
  scope :order_by_created, (lambda do |type_order|
    type_order = type_order.presence || :desc
    order created_at: type_order
  end)
  scope :order_by_status, (lambda do |type_order|
    type_order = type_order.presence || :asc
    order status: type_order
  end)
end

app/controllers/manager/reports_controller.rb
class Manager::ReportsController < ApplicationController
  before_action ->{check_role? :manager}
  before_action :paginate_reports, only: %i(index update)
  before_action :find_report, only: :show

  load_and_authorize_resource

  def index; end

  # rubocop:disable Rails/SkipsModelValidations
  def update
    Report.by_ids(params[:report_ids])
          .update_all status: params[:update_status]
    respond_to do |format|
      format.html{redirect_to manager_reports_path}
      format.js
    end
  end
  # rubocop:enable Rails/SkipsModelValidations

  def show
    checked_new_comment params[:id]
    @user = @report.user
    @comments = Comment.includes_user
                       .by_report_id(params[:id])
                       .order_by_created_at
  end

  private

  def paginate_reports
    select_reports
    per_page = params[:per_page].presence || Settings.paginate.per_page_default
    @reports = @reports.page(params[:page])
                       .per per_page
    return unless params[:show_all]

    @reports = @reports.except :limit, :offset
  end

  def user_in_division
    User.by_division_id(current_user.division_id)
  end

  def find_report
    @report = Report.find_by id: params[:id]
    return if @report

    flash[:danger] = t ".find_report_error"
    redirect_to reports_path
  end

  def select_reports
    users = user_in_division
    @report = Report.ransack params[:q]
    @reports = @report.result
                      .includes(:user)
                      .by_users(users)
                      .active_reports
    return if @report.sorts.present?

    @reports = @reports.order_by_status(:asc)
                       .order_by_created :desc
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action ->{check_role? :member}
  before_action :paginate_reports, only: %i(index destroy)
  before_action :find_report, except: %i(new create index)
  before_action :belong_to_division?, only: %i(new create)
  before_action :today_reports, only: :new

  load_and_authorize_resource

  def index; end

  def new
    return @report = current_user.reports.build if @today_reports.blank?

    flash[:danger] = t ".error_create_path"
    redirect_to reports_path
  end

  def create
    @report = current_user.reports.build report_params

    if @report.save
      flash[:info] = t ".create_success_notify"
      redirect_to reports_path
    else
      flash.now[:danger] = t ".create_failed_notify"
      render :new
    end
  end

  def show
    checked_new_comment params[:id]
    @user = @report.user
    @comments = Comment.includes_user
                       .by_report_id(params[:id])
                       .order_by_created_at
  end

  def update
    if @report.update report_params
      flash[:success] = t ".edit_report_success"
      redirect_to reports_path
    else
      flash[:danger] = t ".edit_report_faild"
      redirect_to edit_report_path params[:id]
    end
  end

  def edit; end

  def destroy
    @report.update deleted: true
    respond_to do |format|
      format.html{redirect_to reports_path}
      format.js
    end
  end

  private

  def report_params
    params.require(:report).permit Report::REPORTS_PARAMS
  end

  def paginate_reports
    select_reports
    per_page = params[:per_page].presence || Settings.paginate.per_page_default
    @reports = @reports.page(params[:page])
                       .per per_page
  end

  def find_report
    @report = Report.find_by id: params[:id]
    return if @report

    flash[:danger] = t ".find_report_error"
    redirect_to reports_path
  end

  def today_reports
    @today_reports = Report.by_users(current_user.id)
                           .by_date_created(Date.current)
                           .active_reports
  end

  def select_reports
    @report = Report.ransack params[:q]
    @reports = @report.result
                      .by_users(current_user.id)
                      .active_reports
                      .recent_reports
  end
end

app/views/reports/_all_report.html.erb
<div>
  <h4>
    <%= t ".all_report" %>
    (<span id="num-reports"><%= reports.total_count %></span>)
  </h4>
</div>
<div class="zui-wrapper">
  <div class="zui-scroller">
    <table class="table table-hover zui-table">
      <thead>
        <tr>
          <th class="zui-sticky-col"><%= t ".id" %></th>
          <th>
            <%= sort_link report, :created_at, t(".date_created") %>
          </th>
          <th><%= t ".today_plan" %></th>
          <th><%= t ".actual" %></th>
          <th><%= t ".tomorrow_plan" %></th>
          <th>
            <%= sort_link report, :status, t(".status") %>
          </th>
          <th class="zui-sticky-col-right"><%= t ".action" %></th>
        </tr>
      </thead>
      <tbody id="tbody-all-report">
        <%= render partial: "report_table", collection: reports, as: :report %>
      </tbody>
    </table>
  </div>
</div>
<% if reports.total_count > Settings.paginate.per_page_default.to_i %>
  <div>
    <span><%= t ".per_page" %></span>
    <% if params[:per_page].eql? Settings.paginate.per_page_option_1 %>
      <%= link_per_page_reports Settings.paginate.per_page_default %>
      <span><%= Settings.paginate.per_page_option_1 %></span>
    <% else %>
      <span><%= Settings.paginate.per_page_default %></span>
      <%= link_per_page_reports Settings.paginate.per_page_option_1 %>
    <% end %>
  </div>
<% end %>
<%= paginate reports %>

app/views/reports/_create_form.html.erb
<%= form_for report do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :today_plan %>
    <span class="require-field">*</span>
    <%= f.text_area :today_plan, class: "form-control", row: Settings.form.num_row %>
  </div>
  <div class="form-group">
    <%= f.label :actual %>
    <span class="require-field">*</span>
    <%= f.text_area :actual, class: "form-control", row: Settings.form.num_row %>
  </div>
  <div class="form-group">
    <%= f.label :reason_not_complete %>
    <%= f.text_area :reason_not_complete, class: "form-control", row: Settings.form.num_row %>
  </div>
  <div class="form-group">
    <%= f.label :tomorrow_plan %>
    <span class="require-field">*</span>
    <%= f.text_area :tomorrow_plan, class: "form-control", row: Settings.form.num_row %>
  </div>
  <div class="form-group">
    <%= f.label :free_comment %>
    <%= f.text_area :free_comment, class: "form-control", row: Settings.form.num_row %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/reports/_filter_form.html.erb
<div class="input-group" id="form-report-filter">
  <%= search_form_for report do |f| %>
    <div class="col-xs-4">
      <p>
        <%= t ".date_created" %>
      </p>
      <%= f.date_field :created_at_eq, class: "input-filter-report" %>
    </div>
    <div class="col-xs-4">
      <p>
        <%= t ".status" %>
      </p>
      <%= f.select :status_eq, Settings.select_option.filter_status, {}, { class: "input-filter-report" } %>
    </div>
    <%= hidden_field_tag :per_page, params[:per_page] %>
    <div class="col-xs-4 div-submit-filter-report">
      <%= f.submit t(".search"), class: "btn btn-success" %>
    </div>
  <% end %>
</div></br>

app/views/reports/_report_table.html.erb
<tr id="<%= "report-#{report.id}" %>" class="<%= "report_new_comment" unless report_new_comment(report.id) %>">
  <td class="zui-sticky-col">
    <%= item_id report_counter, params[:page] %>
  </td>
  <td><%= report.created_at.strftime Settings.date.validate %></td>
  <td><%= report.today_plan.first Settings.report_table_text %></td>
  <td><%= report.actual.first Settings.report_table_text %></td>
  <td><%= report.tomorrow_plan.first Settings.report_table_text %></td>
  <td><%= report.status %></td>
  <td class="zui-sticky-col-right">
    <%= link_to t("detail"), report_path(report.id) %>
    |
    <% if report.waiting? %>
      <%= link_to t(".delete"), report_path(report, status: params[:status], date: params[:date], page: params[:page]), method: :delete, data: { confirm: t(".confirm_delete") }, remote: :true %>
      |
      <%= link_to t(".edit"), edit_report_path(report) %>
    <% end %>
  </td>
</tr>

app/views/reports/destroy.js.erb
$("#tbody-all-report").html(
  "<%= j (render partial: "report_table", collection: @reports, as: :report) %>"
);
$("#num-reports").html("<%= @reports.total_count %>");

app/views/reports/edit.html.erb
<%= provide :title, t(".title") %>
<% provide :button_text, t(".save_change") %>
<div class="col-md-12 box-show">
  <%= render "create_form", report: @report %>
</div>

app/views/reports/index.html.erb
<%= provide :title, t(".daily_report") %>
<div class="div-all-report">
  <h2 class="title-center report-title box-show">
    <%= t ".daily_report" %>
  </h2>
  <div class="box-show">
    <div class="div-create-btn">
      <% unless current_user.division_id.eql? Settings.division.default %>
        <%= link_to t(".create"), new_report_path, class: "btn btn-info", role: "button" %>
      <% end %>
    </div>
    <% if current_user.reports.any? %>
      <div class="div-report-filter">
        <%= render "filter_form", report: @report %>
      </div>
      <div id="all-report">
        <%= render "all_report", reports: @reports, all_reports: @all_reports, report: @report %>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/new.html.erb
<%= provide :title, t(".create_report") %>
<% provide :button_text, t(".create") %>
<h2 class="title-center box-show">
  <%= t ".create_report" %>
</h2>
<div class="div-new-report box-show">
  <div class="div-date-report">
    <%= t ".today" %>
    <%= Date.today %>
  </div>
  <%= render "create_form", report: @report %>
</div>

app/views/reports/show.html.erb
<%= provide :title, t(".title")  %>
<div class="box-show col-xs-9">
  <div>
    <%= render "shared/report_detail", report: @report, user: @user %>
  </div>
  <div class="box-comments report-detail-box col-xs-12">
    <%= render "shared/report_comments", comments: @comments, report: @report %>
  </div>
</div>

app/views/reports/update.js.erb
$("#tbody-all-report").html(
  "<%= j (render partial: "report_table", collection: @reports, as: :report) %>"
);
$("#num-reports").html("<%= reports.total_count %>");