config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "account#index"

    put "/manager/reports", to: "manager/reports#update"

    devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations"
    }, skip: :omniauth_callbacks

    namespace :manager do
      get "/users/search", to: "users#search"
      resources :reports, only: %i(index show update)
      resources :users, only: %i(index show update)
    end

    resources :reports
    resources :account, only: %i(index edit update)
    resources :comments, only: :create
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
        <i class="glyphicon glyphicon-align-left"></i>
        <span>
          <%= t ".toggle_sidebar" %>
        </span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to t(".log_out"), destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav id="sidebar">
  <div class="sidebar-header">
    <h3 id="logo">
      <%= link_to t(".logo"), root_path %>
    </h3>
  </div>
  <ul class="list-unstyled components">
    <% if current_user.member? %>
      <li>
        <%= link_to account_index_path do %>
          <i class="fas fa-user sidebar-icon"></i>
          <%= t ".account" %>
        <% end %>
      </li>
      <li>
        <%= link_to reports_path do %>
          <i class="fas fa-tasks sidebar-icon"></i>
          <%= t ".report" %>
          <div class="pull-right notification" id="side-bar-new-comment-notify">
            <% if new_comment_notify.present? %>
              <span>
                <%= new_comment_notify.count %>
              </span>
            <% end %>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i class="fas fa-list-alt sidebar-icon"></i>
          <%= t ".request" %>
        <% end %>
      </li>
    <% elsif current_user.manager? %>
      <li>
        <%= link_to account_index_path do %>
          <i class="fas fa-user sidebar-icon"></i>
          <%= t ".account" %>
        <% end %>
      </li>
      <li>
        <%= link_to manager_users_path do %>
          <i class="fas fa-users sidebar-icon"></i>
          <%= t ".user" %>
        <% end %>
      </li>
      <li>
        <%= link_to manager_reports_path do %>
          <i class="fas fa-tasks sidebar-icon"></i>
          <%= t ".report" %>
          <div class="pull-right notification" id="side-bar-new-comment-notify">
            <% if new_comment_notify.present? %>
              <span>
                <%= new_comment_notify.count %>
              </span>
            <% end %>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i class="fas fa-list-alt sidebar-icon"></i>
          <%= t ".request" %>
        <% end %>
      </li>
    <% elsif current_user.admin? %>
      <li>
        <%= link_to account_index_path do %>
          <i class="fas fa-user sidebar-icon"></i>
          <%= t ".account" %>
        <% end %>
      </li>
    <% end %>

  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "i18n" %>
    <%= javascript_include_tag "translations", skip_pipeline: true %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="wrapper">
        <%= render "layouts/sidebar" %>
        <div id="content">
          <%= render "layouts/navbar" %>
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    <% else %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    <% end %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript">
        I18n.defaultLocale = "<%= I18n.default_locale %>";
        I18n.locale = "<%= I18n.locale %>";
    </script>
  </body>
</html>